# Generated by Django 5.2.12 on 2026-03-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="設備名稱")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 位址")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("cisco_ios", "Cisco IOS"),
                            ("cisco_nxos", "Cisco NX-OS"),
                            ("juniper_junos", "Juniper JunOS"),
                            ("linux", "Linux Server"),
                            ("generic", "Generic"),
                        ],
                        default="cisco_ios",
                        max_length=50,
                        verbose_name="設備類型",
                    ),
                ),
                (
                    "ssh_username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SSH 帳號"
                    ),
                ),
                (
                    "ssh_password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SSH 密碼"
                    ),
                ),
                ("ssh_port", models.IntegerField(default=22, verbose_name="SSH Port")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("warning", "Warning"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後檢查時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "設備",
                "verbose_name_plural": "設備列表",
            },
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(verbose_name="訊息")),
                ("raw_output", models.TextField(blank=True, verbose_name="原始輸出")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="時間"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="monitor.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備 Log",
                "verbose_name_plural": "設備 Log 列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
