# Generated by Django 6.0.3 on 2026-03-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_device_extra_fields_downtimerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='monitor_interval',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssh_username',
        ),
        migrations.AlterField(
            model_name='downtimerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MonitorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('ping', 'Ping'), ('tcp', 'TCP Port'), ('ssh', 'SSH'), ('http', 'HTTP')], max_length=10, verbose_name='監控類型')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('ssh_username', models.CharField(blank=True, max_length=100, verbose_name='SSH 帳號')),
                ('ssh_password', models.CharField(blank=True, max_length=100, verbose_name='SSH 密碼')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('expected_status_code', models.IntegerField(default=200, verbose_name='預期 HTTP 狀態碼')),
                ('interval', models.IntegerField(default=60, verbose_name='檢查間隔（秒）')),
                ('enabled', models.BooleanField(default=True, verbose_name='啟用')),
                ('last_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='最後狀態')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='最後檢查時間')),
                ('last_message', models.TextField(blank=True, verbose_name='最後訊息')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.device', verbose_name='設備')),
            ],
            options={
                'verbose_name': '監控項目',
                'verbose_name_plural': '監控項目列表',
            },
        ),
    ]
