# Generated by Django 6.0.3 on 2026-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_add_monitorcheck_remove_ssh_from_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('none', '無驗證（直接轉發）'), ('tls', '帳號密碼 + STARTTLS'), ('ssl', '帳號密碼 + SSL'), ('plain', '帳號密碼（無加密）')], default='tls', max_length=10, verbose_name='驗證方式')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP 主機')),
                ('port', models.IntegerField(default=587, verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='帳號')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='密碼')),
                ('from_email', models.CharField(blank=True, max_length=200, verbose_name='寄件者 Email')),
                ('enabled', models.BooleanField(default=False, verbose_name='啟用 Email 功能')),
            ],
            options={
                'verbose_name': 'Email 設定',
            },
        ),
    ]
