# Generated by Django 6.0.5 on 2026-06-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_add_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcheck',
            name='snmp_community',
            field=models.CharField(blank=True, default='public', max_length=100, verbose_name='Community String'),
        ),
        migrations.AddField(
            model_name='monitorcheck',
            name='snmp_port',
            field=models.IntegerField(default=161, verbose_name='SNMP Port'),
        ),
        migrations.AddField(
            model_name='monitorcheck',
            name='snmp_version',
            field=models.IntegerField(default=2, verbose_name='SNMP 版本'),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='check_type',
            field=models.CharField(choices=[('ping', 'Ping'), ('tcp', 'TCP Port'), ('ssh', 'SSH'), ('http', 'HTTP'), ('snmp', 'SNMP')], max_length=10, verbose_name='監控類型'),
        ),
    ]
