# Generated by Django 6.0.5 on 2026-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_add_snmp_to_monitorcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcheck',
            name='snmp_oid',
            field=models.CharField(blank=True, max_length=200, verbose_name='監控 OID'),
        ),
    ]
