# Generated by Django 6.0.5 on 2026-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_add_snmp_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcheck',
            name='snmp_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Interface 名稱'),
        ),
    ]
