# Generated by Django 6.0.5 on 2026-06-11 02:40

import monitor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_add_downtime_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('generic', '一般'), ('cisco_ios', 'Cisco IOS'), ('cisco_nxos', 'Cisco NX-OS'), ('juniper_junos', 'Juniper JunOS'), ('linux', 'Linux Server')], default='generic', max_length=50, verbose_name='設備類型'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='password',
            field=monitor.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='snmp_community',
            field=monitor.fields.EncryptedCharField(blank=True, default='public', max_length=500, verbose_name='Community String'),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='ssh_password',
            field=monitor.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='SSH 密碼'),
        ),
    ]
