# Generated by Django 6.0.5 on 2026-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_encrypt_existing_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=3, verbose_name='監控間隔（秒）')),
            ],
            options={
                'verbose_name': '監控設定',
            },
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='interval',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='檢查間隔（秒）'),
        ),
    ]
