from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_edit, name="profile_edit"),
    path("users/", views.user_list, name="user_list"),
    path("users/add/", views.user_add, name="user_add"),
    path("users/<int:pk>/edit/", views.user_edit, name="user_edit"),
    path("password/change/", views.change_password, name="change_password"),

    path("device/add/", views.device_add, name="device_add"),
    path("device/bulk-add/", views.device_bulk_add, name="device_bulk_add"),
    path("device/bulk-delete/", views.device_bulk_delete, name="device_bulk_delete"),
    path("device/<int:pk>/", views.device_detail, name="device_detail"),
    path("device/<int:pk>/edit/", views.device_edit, name="device_edit"),
    path("device/<int:pk>/delete/", views.device_delete, name="device_delete"),
    path("device/<int:device_pk>/checks/add/", views.monitor_check_add, name="monitor_check_add"),
    path("checks/<int:check_pk>/delete/", views.monitor_check_delete, name="monitor_check_delete"),
    path("checks/<int:check_pk>/toggle/", views.monitor_check_toggle, name="monitor_check_toggle"),

    path("device/orphans/", views.orphan_devices, name="orphan_devices"),
    path("api/device/<int:pk>/assign-company/", views.api_assign_company, name="api_assign_company"),
    path("company/", views.company_list, name="company_list"),
    path("company/<int:pk>/", views.company_detail, name="company_detail"),
    path("company/add/", views.company_add, name="company_add"),
    path("company/<int:pk>/edit/", views.company_edit, name="company_edit"),
    path("company/<int:pk>/delete/", views.company_delete, name="company_delete"),

    path("settings/email/", views.email_settings, name="email_settings"),
    path("settings/email/test/", views.email_test, name="email_test"),

    path("api/status/", views.api_device_status, name="api_status"),
    path("api/device/<int:pk>/status/", views.api_device_detail_status, name="api_device_detail_status"),
    path("api/check-all/", views.api_check_all, name="api_check_all"),
    path("api/device/<int:pk>/check/", views.api_check_device, name="api_check_device"),
    path("api/device/<int:pk>/logs/", views.api_device_logs, name="api_device_logs"),
    path("api/monitor/toggle/", views.api_monitor_toggle, name="api_monitor_toggle"),
    path("api/monitor/status/", views.api_monitor_status, name="api_monitor_status"),
    path("api/monitor/interval/", views.api_monitor_interval, name="api_monitor_interval"),
    path("api/device/<int:pk>/snmp-scan/", views.api_snmp_scan, name="api_snmp_scan"),
    path("api/device/<int:pk>/snmp-add-checks/", views.api_snmp_add_checks, name="api_snmp_add_checks"),
    path("api/checks/<int:check_pk>/edit/", views.api_monitor_check_edit, name="api_monitor_check_edit"),

    path("api/version-check/", views.api_version_check, name="api_version_check"),
    path("api/system-update/", views.api_system_update, name="api_system_update"),
    path("api/system-restart/", views.api_system_restart, name="api_system_restart"),
    path("api/changelog/", views.api_changelog, name="api_changelog"),
    path("logs/duplicate-ip/", views.duplicate_ip_log, name="duplicate_ip_log"),
    path("api/duplicate-ip-log/", views.api_duplicate_ip_log, name="api_duplicate_ip_log"),
    path("api/check-ip/", views.api_check_ip, name="api_check_ip"),
    path("api/ping-check/", views.api_ping_check, name="api_ping_check"),
    path("api/traceroute-check/", views.api_traceroute_check, name="api_traceroute_check"),
]
